# Generated by Django 2.0.6 on 2018-06-29 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('readingwallapi', '0002_auto_20180627_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Done')])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('friendreq_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestedby', to=settings.AUTH_USER_MODEL)),
                ('friendreq_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestedto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
