# Generated by Django 2.0.6 on 2018-06-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readingwallapi', '0003_connections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connections',
            name='request_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Done')], default=0),
        ),
    ]
